# Generated by Django 3.0.2 on 2020-03-22 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VidRubric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'ВидеоРубрика',
                'verbose_name_plural': 'ВидеРубрики',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='ccont',
            name='vrubric',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='board.VidRubric', verbose_name='ВидеоРубрика'),
        ),
    ]
